CREATE TABLE IF NOT EXISTS genres(
    genre_id integer generated by default as identity primary key ,
    genre_name varchar(25)
);

CREATE TABLE IF NOT EXISTS ratings(
    rating_id integer generated by default as identity primary key,
    rating_name varchar(10)
);

CREATE TABLE IF NOT EXISTS films(
    film_id integer generated by default as identity primary key,
    film_name varchar(100),
    film_description varchar(200),
    film_release_date date,
    film_duration integer,
    film_rating_id integer references ratings(rating_id)
);

CREATE TABLE IF NOT EXISTS filmgenres(
    fg_film_id integer references films(film_id),
    fg_genre_id integer references genres(genre_id),
    primary key (fg_film_id,fg_genre_id)
);


CREATE TABLE IF NOT EXISTS users(
    user_id integer generated by default as identity primary key,
    user_email varchar(100),
    user_login varchar(100),
    user_name varchar(100),
    user_birthday date
);

CREATE TABLE IF NOT EXISTS likes(
    l_user_id integer references users(user_id),
    l_film_id integer references films(film_id),
    primary key (l_user_id,l_film_id)
);

CREATE TABLE IF NOT EXISTS userfriends (
    uf_user_id integer references users(user_id),
    uf_friend_id integer references users(user_id),
    primary key (uf_user_id,uf_friend_id)
);
